version: '3'

volumes:
  local_postgres_api_data: {}
  local_postgres_api_data_backups: {}


services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: niki130396/stock-market:django
    container_name: stock_market_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    links:
      - "redis:redis"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: stock_market_platform_api_production_postgres
    container_name: postgres_api
    volumes:
      - local_postgres_api_data:/var/lib/postgresql/data:Z
      - local_postgres_api_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
    ports:
    - "5432:5432"
    restart: always
    hostname: postgres_api

  docs:
    image: stock_market_platform_api_local_docs
    container_name: docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./stock_market_platform_api:/app/stock_market_platform_api:z
    ports:
      - "7000:7000"
    command: /start-docs

  redis:
    image: redis:5.0
    container_name: redis_api
    ports:
    - "6379:6379"
    restart: always
