# Generated by Django 3.0.5 on 2021-03-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_statements', '0002_auto_20210320_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementsmetadata',
            name='market_cap',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
