# Generated by Django 3.0.5 on 2021-05-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_statements', '0003_auto_20210320_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementsmetadata',
            name='is_available',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
