# Generated by Django 3.0.5 on 2021-12-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_statements', '0005_auto_20210613_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementsmetadata',
            name='is_balance_sheet_statement_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statementsmetadata',
            name='is_cash_flow_statement_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statementsmetadata',
            name='is_financial_statement_available',
            field=models.BooleanField(default=False),
        ),
    ]
