# Generated by Django 3.0.5 on 2021-12-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_statements', '0008_statementsmetadata_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementsmetadata',
            name='is_attempted',
            field=models.BooleanField(default=False, help_text='Signals if financial statements for a given symbol have been attempted to be downloaded'),
        ),
    ]
