# Generated by Django 3.0.5 on 2022-05-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_statements', '0009_statementsmetadata_is_attempted'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementsmetadata',
            name='latest_statement_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
