# Generated by Django 3.0.5 on 2021-09-04 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlingSourceDetails',
            fields=[
                ('crawling_source_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('source_type', models.CharField(choices=[('API', 'API'), ('HTML', 'HTML')], default='API', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SourceFields',
            fields=[
                ('field_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('crawling_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='crawling.CrawlingSourceDetails')),
            ],
        ),
    ]
