# Generated by Django 3.0.5 on 2021-09-09 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheetFields',
            fields=[
                ('field_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('crawling_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawling.CrawlingSourceDetails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CashFlowFields',
            fields=[
                ('field_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('crawling_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawling.CrawlingSourceDetails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncomeStatementFields',
            fields=[
                ('field_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('crawling_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawling.CrawlingSourceDetails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SourceFields',
        ),
    ]
