# Generated by Django 3.0.5 on 2021-09-09 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0002_auto_20210909_0534'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IncomeStatementFields',
            new_name='BalanceSheetField',
        ),
        migrations.RenameModel(
            old_name='BalanceSheetFields',
            new_name='CashFlowField',
        ),
        migrations.RenameModel(
            old_name='CashFlowFields',
            new_name='IncomeStatementField',
        ),
    ]
