# Generated by Django 3.0.5 on 2021-09-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0003_auto_20210909_0626'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedField',
            fields=[
                ('field_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
    ]
