# Generated by Django 3.0.5 on 2021-09-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0006_normalizedfield_statement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedfield',
            name='humanized_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
