# Generated by Django 3.0.5 on 2021-09-11 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0007_normalizedfield_humanized_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlingsourcedetails',
            name='normalized_fields',
        ),
    ]
