# Generated by Django 3.0.5 on 2021-09-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0008_remove_crawlingsourcedetails_normalized_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalizedfield',
            name='statement_type',
            field=models.CharField(choices=[('income_statement', 'Income Statement'), ('balance_sheet', 'Balance Sheet'), ('cash_flow', 'Cash Flow'), ('other', 'Other')], default='income_statement', max_length=256),
        ),
    ]
