# Generated by Django 3.0.5 on 2021-09-12 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0010_statementtypedefinition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatementTypeDefinition',
            new_name='StatementTypeSourceDefinition',
        ),
    ]
