# Generated by Django 3.0.5 on 2021-09-12 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0011_auto_20210912_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statementtypesourcedefinition',
            name='crawling_source',
        ),
        migrations.AddField(
            model_name='balancesheetfield',
            name='statement_source_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crawling.StatementTypeSourceDefinition'),
        ),
        migrations.AddField(
            model_name='cashflowfield',
            name='statement_source_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crawling.StatementTypeSourceDefinition'),
        ),
        migrations.AddField(
            model_name='incomestatementfield',
            name='statement_source_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crawling.StatementTypeSourceDefinition'),
        ),
    ]
