# Generated by Django 3.0.5 on 2021-09-24 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0013_auto_20210924_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='normalizedfield',
            old_name='target_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='normalizedfield',
            name='name_from_source',
        ),
    ]
