# Generated by Django 3.0.5 on 2021-09-25 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0014_auto_20210924_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancesheetfield',
            name='statement_source_definition',
        ),
        migrations.RemoveField(
            model_name='cashflowfield',
            name='statement_source_definition',
        ),
        migrations.RemoveField(
            model_name='incomestatementfield',
            name='statement_source_definition',
        ),
        migrations.AddField(
            model_name='statementtypesourcedefinition',
            name='crawling_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crawling.CrawlingSourceDetails'),
        ),
    ]
