# Generated by Django 3.0.5 on 2021-09-26 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0015_auto_20210925_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementTypeLocalDefinition',
            fields=[
                ('statement_type_definition_id', models.AutoField(primary_key=True, serialize=False)),
                ('statement_type_local_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='statementtypesourcedefinition',
            name='crawling_source',
        ),
        migrations.AddField(
            model_name='statementtypesourcedefinition',
            name='local_statement_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crawling.StatementTypeLocalDefinition'),
        ),
    ]
