# Generated by Django 3.0.5 on 2021-09-26 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0016_auto_20210926_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheetfield',
            name='local_statement_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crawling.StatementTypeLocalDefinition'),
        ),
        migrations.AddField(
            model_name='cashflowfield',
            name='local_statement_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crawling.StatementTypeLocalDefinition'),
        ),
        migrations.AddField(
            model_name='incomestatementfield',
            name='local_statement_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crawling.StatementTypeLocalDefinition'),
        ),
    ]
