# Generated by Django 3.0.5 on 2021-09-26 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0017_auto_20210926_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancesheetfield',
            name='local_statement_type',
        ),
        migrations.RemoveField(
            model_name='cashflowfield',
            name='local_statement_type',
        ),
        migrations.RemoveField(
            model_name='incomestatementfield',
            name='local_statement_type',
        ),
        migrations.AddField(
            model_name='statementtypesourcedefinition',
            name='crawling_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crawling.CrawlingSourceDetails'),
        ),
    ]
