# Generated by Django 3.0.5 on 2021-12-25 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0018_auto_20210926_0651'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStatementLine',
            fields=[
                ('field_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('crawling_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawling.CrawlingSourceDetails')),
                ('normalized_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crawling.NormalizedField')),
                ('source_statement_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crawling.StatementTypeSourceDefinition')),
            ],
        ),
    ]
