# Generated by Django 3.0.5 on 2021-12-25 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_statements', '0009_statementsmetadata_is_attempted'),
        ('crawling', '0019_financialstatementline'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStatementFact',
            fields=[
                ('fact_id', models.AutoField(primary_key=True, serialize=False)),
                ('fiscal_year', models.PositiveIntegerField(blank=True, null=True)),
                ('fiscal_period', models.CharField(blank=True, max_length=30, null=True)),
                ('unit', models.CharField(blank=True, max_length=30, null=True)),
                ('value', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial_statements.StatementsMetaData')),
                ('financial_statement_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crawling.FinancialStatementLine')),
            ],
        ),
    ]
