# Generated by Django 3.0.5 on 2022-02-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0022_normalizedfieldtree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalizedfieldtree',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
