# Generated by Django 3.0.5 on 2022-02-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0025_auto_20220211_1152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NormalizedField',
        ),
    ]
