# Generated by Django 3.0.5 on 2022-02-16 14:08

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0028_auto_20220216_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialstatementline',
            name='normalized_field',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crawling.NormalizedFieldTree'),
        ),
    ]
