# Generated by Django 3.0.5 on 2022-02-17 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0029_auto_20220216_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialstatementline',
            name='statement_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crawling.StatementTypeLocalDefinition'),
        ),
    ]
