# Generated by Django 3.0.5 on 2022-05-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0030_auto_20220217_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialstatementfact',
            name='fiscal_year',
        ),
        migrations.AlterField(
            model_name='financialstatementfact',
            name='fiscal_period',
            field=models.DateField(blank=True, null=True),
        ),
    ]
