# Generated by Django 3.0.5 on 2022-05-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0031_auto_20220504_0430'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='normalizedfieldtree',
            index=models.Index(fields=['name'], name='crawling_no_name_c8312c_idx'),
        ),
    ]
