# Generated by Django 3.0.5 on 2022-05-14 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0032_auto_20220512_0452'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='normalizedfieldtree',
            name='crawling_no_name_c8312c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='normalizedfieldtree',
            unique_together=set(),
        ),
    ]
