# Generated by Django 3.0.5 on 2022-05-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0034_incomestatementfieldsmaterializedview'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheetFieldsMaterializedView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('industry', models.CharField(blank=True, max_length=50, null=True)),
                ('sector', models.CharField(blank=True, max_length=50, null=True)),
                ('fiscal_period', models.DateField()),
                ('field_name', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
            ],
            options={
                'db_table': 'balance_sheet_fields',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CashFlowFieldsMaterializedView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('industry', models.CharField(blank=True, max_length=50, null=True)),
                ('sector', models.CharField(blank=True, max_length=50, null=True)),
                ('fiscal_period', models.DateField()),
                ('field_name', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
            ],
            options={
                'db_table': 'cash_flow_fields',
                'managed': False,
            },
        ),
    ]
