# Generated by Django 3.0.5 on 2022-05-24 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_statements', '0010_statementsmetadata_latest_statement_date'),
        ('crawling', '0035_balancesheetfieldsmaterializedview_cashflowfieldsmaterializedview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='financialstatementfact',
            unique_together={('company', 'financial_statement_line', 'fiscal_period')},
        ),
    ]
